[package]
name = "sqlite-rs"
version = "0.3.0"
edition = "2021"
publish = false
license = "Apache-2.0"

[dependencies]
libc = "0.2"
thiserror = "1"

[[test]]
name = "unit_header"
path = "tests/unit/header.rs"

[[test]]
name = "unit_record"
path = "tests/unit/record.rs"

[[test]]
name = "unit_vfs"
path = "tests/unit/vfs.rs"

[dev-dependencies]
proptest = "1"

[lints.clippy]
unwrap_used = "deny"
expect_used = "deny"
indexing_slicing = "deny"
panic = "deny"
arithmetic_side_effects = "deny"
